feat(unsplash): allow user to select multiple topics
the-wright-jamie/tab-nine pull request #137
Opened 2023-11-08 22:24 UTC by nbouliol

## Subtitle of PR

Implements #97

The user can select one or more topics

The selected topics are send to unsplash api that accepts multiple topics

From https://unsplash.com/documentation#get-a-random-photo
> topics | Public topic ID(‘s) to filter selection. If multiple, comma-separated

## Checklist

### Developer Testing Evidence

Evidence of the PR is in action in the section below.

- [ ] Tested in Chrome
- [X] Tested in Firefox
- [ ] Tested in Edge

## Evidence

### Chrome

### Firefox
<img width="1356" alt="image" src="https://github.com/the-wright-jamie/tab-nine/assets/9134195/809313d1-d01a-43c5-8ae2-5443d69cd830">

### Edge

2023-11-09 09:09 UTC, nbouliol commented
It will also enable users to scroll horizontally in the settings inputs (because it was required for the select multiple)

For example in the CSS Snippet textarea

2023-11-09 12:30 UTC, the-wright-jamie requested changes
Looking good, will dev test this myself just to be safe and then merge. In the meantime, please remove the `yarn` lock file 😛

2023-11-09 12:30 UTC, the-wright-jamie commented on yarn.lock
You left your `yarn` lock file in, please remove 🙃

2023-11-13 13:07 UTC, merged

2023-11-14 19:15 UTC, the-wright-jamie commented
Your change has just been published to stores and you should see it locally soon.

For your notes, I made a small modification to your note about selecting multiple topics as I couldn't get it to work without holding down Control. You'll see it, but it looks like this:

| Windows/Linux et al | macOS |
| :-: | :-: |
| ![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/ff46b893-ccfb-43f6-8883-0d521dba7ffd) | ![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/c07408df-b7f8-423d-97a6-34464344112c) |

Thank you once again for your contribution!